install:
	(echo install)
	$(eval BUILD_ARTIFACTS := $(shell pwd)/artifacts/)
	mkdir -p $(BUILD_ARTIFACTS)/{bin,lib}

	# install memcached
	(install -D -m755 ./workloads/data_caching/memcached/memcached-1.4.25/build/memcached ${BUILD_ARTIFACTS}/bin)
	# install mutilate
	(install -D -m755 ./workloads/data_caching/memcached/mutilate/mutilate ${BUILD_ARTIFACTS}/bin)
	# install low level aggressors
	(install -D -m755 ./workloads/low-level-aggressors/{l1d,l1i,l3,memBw,stream.100M} ${BUILD_ARTIFACTS}/bin)
	# copy go binaries
	(cp ${GOPATH}/bin/* ${BUILD_ARTIFACTS}/bin)
	
	# install specjbb
	(install -d ${ARTIFACTS_PATH}/share/specjbb)
	(install -d ${ARTIFACTS_PATH}/share/specjbb/config)
	(install -d ${ARTIFACTS_PATH}/share/specjbb/lib)
	(install -D -m755 ./workloads/web_serving/specjbb/specjbb2015.jar ${ARTIFACTS_PATH}/share/specjbb/specjbb2015.jar)
	(install -D -m644 ./workloads/web_serving/specjbb/config/* ${ARTIFACTS_PATH}/share/specjbb/config/)
	(install -D -m644 ./workloads/web_serving/specjbb/lib/* ${ARTIFACTS_PATH}/share/specjbb/lib/)
