package mocks

import (
	"github.com/stretchr/testify/mock"
	"time"
)

// This is an autogenerated mock type for the LoadGenerator type
type LoadGenerator struct {
	mock.Mock
}

// Load provides a mock function with given fields: qps, duration
func (_m *LoadGenerator) Load(qps int, duration time.Duration) (int, error) {
	ret := _m.Called(qps, duration)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, time.Duration) int); ok {
		r0 = rf(qps, duration)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, time.Duration) error); ok {
		r1 = rf(qps, duration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Populate provides a mock function with given fields:
func (_m *LoadGenerator) Populate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Tune provides a mock function with given fields: slo
func (_m *LoadGenerator) Tune(slo int) (int, error) {
	ret := _m.Called(slo)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(slo)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(slo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
