install: build_workloads build_swan
	(echo install)
	$(eval BUILD_ARTIFACTS := $(shell pwd)/artifacts/)
	mkdir -p $(BUILD_ARTIFACTS)/{bin,lib}

	# install memcached
	(install -D -m755 ./workloads/data_caching/memcached/memcached-1.4.25/build/memcached ${BUILD_ARTIFACTS}/bin)
	# install mutilate
	(install -D -m755 ./workloads/data_caching/memcached/mutilate/mutilate ${BUILD_ARTIFACTS}/bin)
	# install low level aggressors
	(install -D -m755 ./workloads/low-level-aggressors/{l1d,l1i,l3,memBw,stream.100M} ${BUILD_ARTIFACTS}/bin)
	# copy go binaries
	(cp ${GOPATH}/bin/* ${BUILD_ARTIFACTS}/bin)
	
	# install specjbb
	(install -d ${BUILD_ARTIFACTS}/share/specjbb)
	(install -d ${BUILD_ARTIFACTS}/share/specjbb/config)
	(install -d ${BUILD_ARTIFACTS}/share/specjbb/lib)
	(install -D -m755 ./workloads/web_serving/specjbb/specjbb2015.jar ${BUILD_ARTIFACTS}/share/specjbb/specjbb2015.jar)
	(install -D -m644 ./workloads/web_serving/specjbb/config/* ${BUILD_ARTIFACTS}/share/specjbb/config/)
	(install -D -m644 ./workloads/web_serving/specjbb/lib/*.jar ${BUILD_ARTIFACTS}/share/specjbb/lib/)

	# install caffe
	(install -d ${BUILD_ARTIFACTS}/share/caffe)
	(install -D -m755 ./workloads/deep_learning/caffe/caffe_wrapper.sh "${BUILD_ARTIFACTS}/bin/caffe")
	
	(install -D -m644 ./workloads/deep_learning/caffe/caffe_src/build/lib/* "${BUILD_ARTIFACTS}/lib")
	
	(install -D -m755 ./workloads/deep_learning/caffe/caffe_src/build/tools/caffe.bin "${BUILD_ARTIFACTS}/share/caffe/bin/caffe")
	(install -D -m755 ./workloads/deep_learning/caffe/caffe_src/data/cifar10/get_cifar10.sh "${BUILD_ARTIFACTS}/share/caffe/data/cifar10/get_cifar10.sh")	
	(install -D -m755 ./workloads/deep_learning/caffe/caffe_src/build/tools/compute_image_mean "${BUILD_ARTIFACTS}/share/caffe/build/tools/compute_image_mean")
	(install -D -m755 ./workloads/deep_learning/caffe/caffe_src/build/examples/cifar10/convert_cifar_data.bin "${BUILD_ARTIFACTS}/share/caffe/build/examples/cifar10/convert_cifar_data.bin")
	(install -D -m644 ./workloads/deep_learning/caffe/cifar10_quick_iter_5000.caffemodel.h5 "${BUILD_ARTIFACTS}/share/caffe/cifar10_quick_iter_5000.caffemodel.h5")
	
	(install -d ${BUILD_ARTIFACTS}/share/caffe/examples/cifar10/)
	(install -D -m644 ./workloads/deep_learning/caffe/caffe_src/examples/cifar10/* "${BUILD_ARTIFACTS}/share/caffe/examples/cifar10/") 

	# pack
	(tar -czf artifacts.tgz -C ${BUILD_ARTIFACTS} .)
