package mocks

import "github.com/stretchr/testify/mock"

// OptionInt is an autogenerated mock type for the OptionInt type
type OptionInt struct {
	mock.Mock
}

// Empty provides a mock function with given fields:
func (_m *OptionInt) Empty() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields:
func (_m *OptionInt) Get() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetOrElse provides a mock function with given fields: _a0
func (_m *OptionInt) GetOrElse(_a0 int) int {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
