FROM centos:7

MAINTAINER https://github.com/intelsdi-x/swan

ENV GOPATH=/opt/gopath \
    PATH=/usr/local/go/bin:/opt/gopath/bin:$PATH \
    GIT_TERMINAL_PROMPT=1

ADD workload_deps_centos/ /workload_deps_centos/
ADD install_deps.sh /workload_deps_centos/

RUN yum install -y epel-release && \
    yum groupinstall -y 'Development Tools' && \
    yum install -y \
        cppzmq-devel \
        gengetopt \
        git \
        libevent-devel \
        libcgroup \
        libcgroup-tools \
        nc \
        scons \
        sudo \
        wget \
        which && \
    (cd workload_deps_centos && ./install_deps.sh) && \
    yum clean all && \
    wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp -O /usr/local/include/zmq.hpp && \
    wget https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz -O /usr/local/go.tar.gz && \
    cd /usr/local/ && \
    tar xfvv go.tar.gz && \
    mkdir /opt/gopath

WORKDIR /opt/gopath/src/github.com/intelsdi-x
ADD swan_scripts /

ENTRYPOINT ["/start.sh"]
CMD ["-t make -s integration_tests"]
