FROM centos:7

MAINTAINER https://github.com/intelsdi-x/swan

ENV GOPATH=/opt/gopath \
    PATH=/usr/local/go/bin:/opt/gopath/bin:$PATH \
    GIT_TERMINAL_PROMPT=1

ADD misc/dev/docker/workload_deps_centos/ /workload_deps_centos/
ADD misc/dev/docker/install_deps.sh /workload_deps_centos/

RUN yum install -y epel-release && \
    yum groupinstall -y 'Development Tools' && \
    yum install -y \
        cppzmq-devel \
        gengetopt \
        git \
        libevent-devel \
        libcgroup \
        libcgroup-tools \
        nc \
        numactl \
        moreutils-parallel \
        scons \
        sudo \
        wget \
        which && \
    (cd workload_deps_centos && ./install_deps.sh) && \
    yum clean all && \
    wget https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz -O /usr/local/go.tar.gz && \
    cd /usr/local/ && \
    tar xfvv go.tar.gz

ADD . /opt/gopath/src/github.com/intelsdi-x/swan
RUN cd /opt/gopath/src/github.com/intelsdi-x/swan && \
    adduser memcached && \
    make build_workloads

WORKDIR /opt/gopath/src/github.com/intelsdi-x
ADD misc/dev/docker/swan_scripts /

ENTRYPOINT ["/start.sh"]
