FROM ubuntu:16.04

MAINTAINER https://github.com/intelsdi-x/swan

ENV GOPATH=/opt/gopath \
    PATH=/usr/local/go/bin:/opt/gopath/bin:$PATH \
    GIT_TERMINAL_PROMPT=1

ADD misc/dev/docker/workload_deps_ubuntu/ /workload_deps_ubuntu/
ADD misc/dev/docker/install_deps.sh /workload_deps_ubuntu/

RUN apt-get update && \
    apt-get install -y build-essential \
        automake \
        cgroup-bin \
        gengetopt \
        git \
        libevent-dev \
        libcgroup-dev \
        libzmq5-dev \
        netcat \
        numactl \
        scons \
        sudo \
        wget && \
    (cd workload_deps_ubuntu && ./install_deps.sh) && \
    apt-get clean && \
    ln -s /usr/bin/automake /usr/bin/automake-1.13 && \
    ln -s /usr/bin/aclocal /usr/bin/aclocal-1.13 && \
    ln -s /usr/bin/autoconf /usr/bin/autoconf-1.13 && \
    cp /usr/sbin/useradd /usr/sbin/adduser && \
    wget https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz -O /usr/local/go.tar.gz && \
    cd /usr/local/ && \
    tar xfvv go.tar.gz

ADD . /opt/gopath/src/github.com/intelsdi-x/swan
RUN cd /opt/gopath/src/github.com/intelsdi-x/swan && \
    adduser memcached && \
    make build_workloads

WORKDIR /opt/gopath/src/github.com/intelsdi-x
ADD misc/dev/docker/swan_scripts /

ENTRYPOINT ["/start.sh"]
