FROM ubuntu:16.04

MAINTAINER https://github.com/intelsdi-x/swan

ENV GOPATH=/opt/gopath \
    PATH=/usr/local/go/bin:/opt/gopath/bin:$PATH \
    GIT_TERMINAL_PROMPT=1

ADD workload_deps_ubuntu/ /workload_deps_ubuntu/
ADD install_deps.sh /workload_deps_ubuntu/

RUN apt-get update && \
    apt-get install -y build-essential \
        automake \
        cgroup-bin \
        gengetopt \
        git \
        libevent-dev \
        libcgroup-dev \
        libzmq5-dev \
        netcat \
        scons \
        sudo \
        wget && \
    (cd workload_deps_ubuntu && ./install_deps.sh) && \
    apt-get clean && \
    ln -s /usr/bin/automake /usr/bin/automake-1.13 && \
    ln -s /usr/bin/aclocal /usr/bin/aclocal-1.13 && \
    ln -s /usr/bin/autoconf /usr/bin/autoconf-1.13 && \
    ln -s /usr/lib/x86_64-linux-gnu/libzmq.so.5 /usr/lib/x86_64-linux-gnu/libzmq.so.4 && \
    cp /usr/sbin/useradd /usr/sbin/adduser && \
    wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp -O /usr/local/include/zmq.hpp && \
    wget https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz -O /usr/local/go.tar.gz && \
    cd /usr/local/ && \
    tar xfvv go.tar.gz && \
    mkdir /opt/gopath

WORKDIR /opt/gopath/src/github.com/intelsdi-x
ADD swan_scripts /

ENTRYPOINT ["/start.sh"]
CMD ["-t make -s integration_tests"]
