package kubernetes

import mock "github.com/stretchr/testify/mock"
import v1 "k8s.io/client-go/pkg/api/v1"

// mockK8sPodAPI is an autogenerated mock type for the k8sPodAPI type
type mockK8sPodAPI struct {
	mock.Mock
}

// getPodsFromNode provides a mock function with given fields: nodeName
func (_m *mockK8sPodAPI) getPodsFromNode(nodeName string) ([]v1.Pod, error) {
	ret := _m.Called(nodeName)

	var r0 []v1.Pod
	if rf, ok := ret.Get(0).(func(string) []v1.Pod); ok {
		r0 = rf(nodeName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Pod)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// killPods provides a mock function with given fields: pods
func (_m *mockK8sPodAPI) killPods(pods []v1.Pod) error {
	ret := _m.Called(pods)

	var r0 error
	if rf, ok := ret.Get(0).(func([]v1.Pod) error); ok {
		r0 = rf(pods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ k8sPodAPI = (*mockK8sPodAPI)(nil)
