// Code generated by mockery v1.0.0
package executor

import mock "github.com/stretchr/testify/mock"

// MockLauncher is an autogenerated mock type for the Launcher type
type MockLauncher struct {
	mock.Mock
}

// Launch provides a mock function with given fields:
func (_m *MockLauncher) Launch() (TaskHandle, error) {
	ret := _m.Called()

	var r0 TaskHandle
	if rf, ok := ret.Get(0).(func() TaskHandle); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TaskHandle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// String provides a mock function with given fields:
func (_m *MockLauncher) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
