package executor

import mock "github.com/stretchr/testify/mock"
import os "os"

// MockTaskInfo is an autogenerated mock type for the TaskInfo type
type MockTaskInfo struct {
	mock.Mock
}

// Address provides a mock function with given fields:
func (_m *MockTaskInfo) Address() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ExitCode provides a mock function with given fields:
func (_m *MockTaskInfo) ExitCode() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Status provides a mock function with given fields:
func (_m *MockTaskInfo) Status() TaskState {
	ret := _m.Called()

	var r0 TaskState
	if rf, ok := ret.Get(0).(func() TaskState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(TaskState)
	}

	return r0
}

// StderrFile provides a mock function with given fields:
func (_m *MockTaskInfo) StderrFile() (*os.File, error) {
	ret := _m.Called()

	var r0 *os.File
	if rf, ok := ret.Get(0).(func() *os.File); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StdoutFile provides a mock function with given fields:
func (_m *MockTaskInfo) StdoutFile() (*os.File, error) {
	ret := _m.Called()

	var r0 *os.File
	if rf, ok := ret.Get(0).(func() *os.File); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// String provides a mock function with given fields:
func (_m *MockTaskInfo) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
