# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#!/usr/bin/env bash
# q -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Variables
  #aws_data_file      = "#{ENV['HOME']}/.vagrant/aws-creds"
  vagrant_user       = ENV['VAGRANT_USER'] || 'vagrant'
  home_dir           = vagrant_user == 'root' ? '/root/' : "/home/#{vagrant_user}"
  build_cached_image = ENV["BUILD_CACHED_IMAGE"] == 'true' ? true : false
  share_glide_cache  = ENV["SHARE_GLIDE_CACHE"] || false

  provision_development_environment = ENV["SWAN_DEVELOPMENT_ENVIRONMENT"] == 'true' ? true : false

  # Vagrant Box configs
  config.vm.box_check_update = false

  # SSH agent forwarding (for host private keys)
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  #config.ssh.keys_only = false
  #config.ssh.insert_key = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".." ,
                          "#{home_dir}/go/src/github.com/intelsdi-x/swan",
                          mount_options: ["umask=0022,dmask=0022,fmask=0022"],
                          type: "rsync"

#  if File.directory?(File.expand_path("#{ENV['HOME']}/swan_s3_creds"))
#       config.vm.synced_folder "#{ENV['HOME']}/swan_s3_creds",
#                               "#{home_dir}/swan_s3_creds",
#                               :mount_options => ["umask=0022,dmask=0022,fmask=0022"],
#                               type: "rsync"
#  end

  # VirtualBox provider
  config.vm.provider "virtualbox" do |vb, override|

    # Vagrant Box config
    override.vm.box = "centos/7"

    # SSH config
    #override.ssh.insert_key = true
    #override.ssh.keys_only = true

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    override.vm.network "private_network", ip: "10.141.141.10"

    vb.name = "swan"
    vb.gui  = false

    # NOTE: integration tests fail with less than 2 vCPUs
    #       integration tests tend to crash with less than 4GB RAM (gcc)
    vb.cpus   = (ENV['VBOX_CPUS'] != '' && ENV['VBOX_CPUS'] || 2)
    vb.memory = (ENV['VBOX_MEM']  != '' && ENV['VBOX_MEM']  || 4096)

    # Share glide cache with guest box
    if share_glide_cache
      override.vm.synced_folder "#{ENV['HOME']}/.glide",
                                "#{home_dir}/.glide",
                                :mount_options => ["umask=0022,dmask=0022,fmask=0022"],
                                type: "rsync"
    end

    override.vm.provision "shell", path: "provision.sh", env:
      {
        'VAGRANT_USER' => vagrant_user,
        'HOME_DIR' => home_dir,
        'SWAN_DEVELOPMENT_ENVIRONMENT' => provision_development_environment
      }
  end
  # Env VirtualBox provider

  # OpenStack provider
  config.vm.provider :openstack do |os, override|

    # SSH config
    override.ssh.username = "centos"
    #override.ssh.insert_key = true

    # Auth config
    os.identity_api_version = "3"
    os.openstack_auth_url   = ENV['OS_AUTH_URL']
    os.tenant_name          = ENV['OS_TENANT_NAME']
    os.project_name         = ENV['OS_PROJECT_NAME']
    os.domain_name          = ENV['OS_USER_DOMAIN_NAME']
    os.username             = ENV['OS_USERNAME']
    os.password             = ENV['OS_PASSWORD']
    os.region               = ENV['OS_REGION_NAME']

    # VM config
    os.server_name      = "swan-ci"
    os.image            = ENV['OS_IMAGE_ID']
    os.flavor           = ENV['OS_FLAVOR_ID']
    os.floating_ip_pool = ENV['OS_FLOATING_POOL'] || "external"
    os.networks         = ENV['OS_NETWORK_ID']
    os.security_groups  = [ "default" ]

    # User data
    # requiretty cannot be set in sudoers for vagrant to work
    os.user_data = "#!/bin/bash\nsed -i 's/Defaults    requiretty/#Defaults    requiretty/' /etc/sudoers"

    # Provisioning
    if build_cached_image
      override.vm.provision "shell", path: "provision.sh", env:
        {
          'VAGRANT_USER' => vagrant_user,
          'HOME_DIR' => home_dir,
          'SWAN_DEVELOPMENT_ENVIRONMENT' => provision_development_environment
        }
    end
  end
  # End Openstack provider

end
