package mocks

import "github.com/stretchr/testify/mock"

// SessionHandle is an autogenerated mock type for the SessionHandle type
type SessionHandle struct {
	mock.Mock
}

// Stop provides a mock function with given fields:
func (_m *SessionHandle) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
