default: 
	g++ -o memCap memCap.c
	g++ -o memBench memBench.c
	g++ -o memCapAlt memCapAlt.c
	g++ -o memBw memBw.c
	g++ -o l1i l1i.c -lrt
	g++ -o l1d l1d.c -lrt
	g++ -o l3 l3.c -lrt

clean: 
	rm memCap
	rm memBench
	rm memCapAlt
	rm memBw
	rm l1i
	rm l1d
	rm l3
