---

- name: install docker
  include_role:
    name: docker

- name: register systemd service
  systemd: name=cassandra
  register: cassandra_service

- name: create resources directory
  file:
    path: "{{ swan_location }}/resources"
    state: directory
  when: cassandra_service.status.SubState != "running"

- name: copy cassandra service
  template:
    src: cassandra.service.j2
    dest: "{{ systemd_unit_location }}/cassandra.service"
  when: cassandra_service.status.SubState != "running"

- name: copy cassandra keyspace
  template:
    src: keyspace.cql.j2
    dest: "{{ swan_location }}/resources/keyspace.cql"
  when: cassandra_service.status.SubState != "running"

- name: copy cassandra table
  template:
    src: table.cql.j2
    dest: "{{ swan_location }}/resources/table.cql"
  when: cassandra_service.status.SubState != "running"

- name: Pull Cassandra image
  docker_image:
    name: cassandra
    tag: 3.5
  when: cassandra_service.status.SubState != "running"

- name: Prepare Cassandra storage directory
  file:
    path: /var/data/cassandra
    state: directory
  when: cassandra_service.status.SubState != "running"

- name: Run and enable Cassandra daemon
  systemd:
    name: cassandra
    enabled: yes
    state: restarted
  when: cassandra_service.status.SubState != "running"
