package snap

import executor "github.com/intelsdi-x/swan/pkg/executor"
import mock "github.com/stretchr/testify/mock"

// MockSessionLauncher is an autogenerated mock type for the SessionLauncher type
type MockSessionLauncher struct {
	mock.Mock
}

// LaunchSession provides a mock function with given fields: monitoredTask, tags
func (_m *MockSessionLauncher) LaunchSession(monitoredTask executor.TaskInfo, tags map[string]interface{}) (executor.TaskHandle, error) {
	ret := _m.Called(monitoredTask, tags)

	var r0 executor.TaskHandle
	if rf, ok := ret.Get(0).(func(executor.TaskInfo, map[string]interface{}) executor.TaskHandle); ok {
		r0 = rf(monitoredTask, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(executor.TaskHandle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(executor.TaskInfo, map[string]interface{}) error); ok {
		r1 = rf(monitoredTask, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ SessionLauncher = (*MockSessionLauncher)(nil)
