---

- name: downloading go
  get_url:
    url: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/cache/go-{{ go_version }}"

- name: unpacking go
  unarchive:
    src: "/cache/go-{{ go_version }}"
    dest: "/usr/local"
    remote_src: true

- name: downloading glide
  get_url:
    url: "https://github.com/Masterminds/glide/releases/download/{{ glide_version }}/glide-{{ glide_version }}-linux-amd64.tar.gz"
    dest: "/cache/glide-{{ glide_version }}"

- name: creating glide temp
  file:
    path: /tmp/glide
    state: directory

- name: unpacking glide
  unarchive:
    src: "/cache/glide-{{ glide_version }}"
    dest: "/tmp/glide"
    remote_src: true

- name: installing glide
  copy:
    src: "/tmp/glide/linux-amd64/glide"
    dest: "/usr/bin/glide"
    remote_src: true
    mode: 0755

- name: cleaning up glide temp
  file:
    path: /tmp/glide
    state: absent

- name: downloading godep
  get_url:
    url: "https://github.com/tools/godep/releases/download/{{ godep_version }}/godep_linux_amd64"
    dest: "/cache/godep-{{ godep_version }}"

- name: installing godep
  copy:
    src: "/cache/godep-{{ godep_version }}"
    dest: "/usr/bin/godep"
    remote_src: true
    mode: 0755
