---
- hosts: swan-test
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
    - name: Create /opt/swan
      file:
        path: /opt/swan
        state: directory
    - name: Copy Swan binaries
      copy:
        src: ~/go/src/github.com/intelsdi-x/swan/build/
        dest: /opt/swan
    - name: Copy Swan services
      copy:
        src: ~/go/src/github.com/intelsdi-x/swan/vagrant/
        dest: /swan_services
    - name: Experiment environment provisioning script run
      environment:
        SWAN_USER: "{{ swan_user }}"
        HOME_DIR: "{{ home_dir }}"
        SWAN_SERVICES_DIR: "{{ swan_services_dir }}"
      script: ~/go/src/github.com/intelsdi-x/swan/vagrant/provision_experiment_environment.sh
    - name: Install Mutilate
      script: ~/go/src/github.com/intelsdi-x/swan/ansible/install_mutilate.sh

