FROM centos:7

MAINTAINER https://github.com/intelsdi-x/swan

ENV GOPATH=/opt/gopath \
    PATH=/usr/local/go/bin:/opt/gopath/bin:$PATH \
    GIT_TERMINAL_PROMPT=1

RUN yum install -y epel-release && \
    yum groupinstall -y 'Development Tools' && \
    yum install -y \
        gengetopt \
        git \
        libevent-devel \
        libcgroup \
        libcgroup-tools \
        nc \
        scons \
        sudo \
        wget \
        which \
	protobuf \
	protobuf-devel \
	leveldb \
	leveldb-devel \
	snappy \
    	snappy-devel \
	opencv \
	opencv-devel \
	boost \
	boost-devel \
	hdf5 \
	hdf5-devel \
    	gflags \
	glog \
	lmdb \
	gflags-devel \
	glog-devel \
	lmdb-devel 
	openblas \
	openblas-devel && \
    yum clean all && \
    wget https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz -O /usr/local/go.tar.gz && \
    cd /usr/local/ && \
    tar xfvv go.tar.gz && \
    mkdir /opt/gopath

WORKDIR /opt/
ADD start.sh /start.sh

ENTRYPOINT ["/start.sh"]
CMD ["lint integration_test"]
